export * from './Settings'
export * from './Home'
export * from './ArrowLeft'

export * from './Logo'

export * from './Homepage'
export * from './Singlepage'
export * from './ArrowRight'
export * from './Publishing'
export * from './Appdesign'
export * from './Consulting'
export * from './News'
export * from './Notice'
export * from './Banner'
export * from './NotFound'

export * from './Youtube'
export * from './Twitter'
export * from './Instagram'
