export * from '~/queries/root'
export * from '~/queries/post'
export { default as posts } from '~/queries/posts'
export { default as news } from '~/queries/news'
export { default as notices } from '~/queries/notices'
export { default as dev } from '~/queries/dev'
export { default as design } from '~/queries/design'
export { default as uiux } from '~/queries/uiux'
export { default as badminton } from '~/queries/badminton'
export * from '~/queries/promotion'
export * from '~/queries/main'
export * from '~/queries/services'
