export * from '~/queries/root'
export * from '~/queries/posts'
export * from '~/queries/news'
export * from '~/queries/notices'
export * from '~/queries/promotion'
export * from '~/queries/promotions'
export * from '~/queries/services/homepage'
