export * from '~/queries/root'
export * from '~/queries/posts'
export { default as news } from '~/queries/news'
export { default as notices } from '~/queries/notices'
export * from '~/queries/promotion'
export * from '~/queries/main'
export * from '~/queries/services'
